GENERATED = .gitignore cleaned-bullet-src package package.tar.gz
LIB_NAMES = openal-soft ogg vorbis alure zlib physfs lua lua-cjson glfw bullet glm

all: package.tar.gz

clean:
	rm -rf $(GENERATED)

.PHONY: all clean

.gitignore: Makefile
	echo '# FILE IS GENERATED BY MAKE - DO NOT EDIT' > $@
	echo '/config.mk' >> $@
	for file in $(GENERATED) ; do \
		echo /$$file >> $@ ; \
	done

cleaned-bullet-src: Makefile src/bullet
	rm -rf $@
	mkdir $@
	cp -R src/bullet/src/* $@/
	find $@ -not -type d -and -not -name '*.h' -delete
	rm -rf $@/Bullet3*
	rm -rf $@/clew

package: Makefile cleaned-bullet-src $(addprefix build/,$(filter-out glm,$(LIB_NAMES))) src/glm
	rm -rf $@
	mkdir $@
	mkdir $@/licenses
	# openal-soft:
	cp src/openal-soft/COPYING $@/licenses/openal-soft.txt
	cp -R src/openal-soft/include/AL $@/AL
	cp build/openal-soft/OpenAL32$(SHARED_LIBRARY_POSTFIX) $@/
	# ogg:
	mkdir $@/ogg
	cp src/ogg/COPYING $@/licenses/ogg.txt
	cp src/ogg/include/ogg/*.h $@/ogg/
	cp build/ogg/include/ogg/*.h $@/ogg/
	cp build/ogg/src/.libs/libogg.a $@/
	# vorbis:
	mkdir $@/vorbis
	cp src/vorbis/COPYING $@/licenses/vorbis.txt
	cp src/vorbis/include/vorbis/*.h $@/vorbis/
	cp build/vorbis/lib/.libs/*.a $@/
	# alure:
	cp src/alure/COPYING $@/licenses/alure.txt
	cp src/alure/include/alext.h $@/
	cp -R src/alure/include/AL $@/
	cp build/alure/libALURE32-static.a $@/libalure.a
	# zlib:
	cp zlib-LICENSE.txt $@/licenses/zlib.txt
	cp src/zlib/*.h $@/
	cp build/zlib/*.h $@/
	cp build/zlib/libzlibstatic.a $@/libzlib.a
	# physfs:
	cp src/physfs/LICENSE.txt $@/licenses/physfs.txt
	cp src/physfs/physfs.h $@/
	cp build/physfs/libphysfs.a $@/
	# lua:
	cp lua-LICENSE.txt $@/licenses/lua.txt
	cp build/lua/src/*.h $@/
	cp build/lua/src/liblua.a $@/
	# lua-cjson:
	cp src/lua-cjson/LICENSE $@/licenses/lua-cjson.txt
	cp src/lua-cjson/lua_cjson.h $@/
	cp build/lua-cjson/cjson.a $@/liblua-cjson.a
	# glfw:
	cp src/glfw/COPYING.txt $@/licenses/glfw.txt
	cp -R src/glfw/include/GLFW $@/GLFW
	cp build/glfw/src/libglfw3.a $@/libglfw.a
	# bullet:
	cp -R cleaned-bullet-src/* $@/
	cp bullet-LICENSE.txt $@/licenses/bullet.txt
	cp build/bullet/lib/*.a $@/
	# glm:
	cp src/glm/copying.txt $@/licenses/glm.txt
	cp -R src/glm/glm $@/glm
	rm $@/glm/CMakeLists.txt
	# extra:
	cp $(EXTRA_FILES) $@/

package.tar.gz: Makefile package
	tar czvf $@ -C package .

include config.mk
include src/makefile.mk
include build/makefile.mk
