include config.mk
GENERATED = .gitignore cleaned-bullet-src package package.tar.gz

all:
	cd src   && $(MAKE)
	cd build && $(MAKE)
	$(MAKE) $(GENERATED)

clean:
	cd src   && $(MAKE) clean
	cd build && $(MAKE) clean
	rm -fr $(GENERATED)

.PHONY: all clean

.gitignore:
	echo '# FILE IS GENERATED BY MAKE - DO NOT EDIT' > $@
	echo '/config.mk' >> $@
	for file in $(GENERATED) ; do \
		echo /$$file >> $@ ; \
	done

cleaned-bullet-src:
	mkdir $@
	cp -R src/bullet/src/* $@/
	find $@ -not -type d -and -not -name '*.h' -delete
	rm -rf $@/Bullet3* $@/clew

package: cleaned-bullet-src build/openal-soft build/ogg build/vorbis build/alure build/zlib build/physfs build/lua build/lua-cjson build/glfw build/bullet
	mkdir $@
	mkdir $@/licenses
	# openal-soft:
	cp src/openal-soft/COPYING $@/licenses/openal-soft.txt
	cp -R src/openal-soft/include/AL $@/AL
	cp build/openal-soft/OpenAL32$(SHARED_LIBRARY_POSTFIX) $@/
	# ogg:
	mkdir $@/ogg
	cp src/ogg/COPYING $@/licenses/ogg.txt
	cp src/ogg/include/ogg/*.h $@/ogg/
	cp build/ogg/include/ogg/*.h $@/ogg/
	cp build/ogg/src/.libs/libogg.a $@/
	# vorbis:
	mkdir $@/vorbis
	cp src/vorbis/COPYING $@/licenses/vorbis.txt
	cp src/vorbis/include/vorbis/*.h $@/vorbis/
	cp build/vorbis/lib/.libs/*.a $@/
	# alure:
	cp src/alure/COPYING $@/licenses/alure.txt
	cp src/alure/include/alext.h $@/
	cp -R src/alure/include/AL $@/
	cp build/alure/libALURE32-static.a $@/libalure.a
	# zlib:
	cp zlib-LICENSE.txt $@/licenses/zlib.txt
	cp src/zlib/*.h $@/
	cp build/zlib/*.h $@/
	cp build/zlib/libzlibstatic.a $@/libzlib.a
	# physfs:
	cp src/physfs/LICENSE.txt $@/licenses/physfs.txt
	cp src/physfs/physfs.h $@/
	cp build/physfs/libphysfs.a $@/
	# lua:
	cp lua-LICENSE.txt $@/licenses/lua.txt
	cp build/lua/src/*.h $@/
	cp build/lua/src/liblua.a $@/
	# lua-cjson:
	cp src/lua-cjson/LICENSE $@/licenses/lua-cjson.txt
	cp src/lua-cjson/lua_cjson.h $@/
	cp build/lua-cjson/cjson.a $@/liblua-cjson.a
	# glfw:
	cp src/glfw/COPYING.txt $@/licenses/glfw.txt
	cp src/glfw/src/*.h $@/
	cp build/glfw/src/*.h $@/
	cp build/glfw/src/libglfw3.a $@/libglfw.a
	# bullet:
	cp -R cleaned-bullet-src/* $@/
	cp bullet-LICENSE.txt $@/licenses/bullet.txt
	cp build/bullet/lib/*.a $@/

package.tar.gz:
	tar czvf $@ -C package .
